// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GooglePlayConstants
{
        public const string achievement_im_still_good_at_this = "CgkIifHX39oVEAIQBA"; // <GPGSID>
        public const string achievement_skill_level_asian_starcraft_pro = "CgkIifHX39oVEAIQCQ"; // <GPGSID>
        public const string achievement_breaking_the_sound_barrier = "CgkIifHX39oVEAIQBg"; // <GPGSID>
        public const string achievement_with_the_speed_of_light = "CgkIifHX39oVEAIQCg"; // <GPGSID>
        public const string achievement_godlike = "CgkIifHX39oVEAIQCw"; // <GPGSID>
        public const string achievement_fast_and_furious = "CgkIifHX39oVEAIQBQ"; // <GPGSID>
        public const string achievement_skill_level_starcraft_pro = "CgkIifHX39oVEAIQCA"; // <GPGSID>
        public const string achievement_im_just_warming_up = "CgkIifHX39oVEAIQAw"; // <GPGSID>
        public const string achievement_good_old_times = "CgkIifHX39oVEAIQAg"; // <GPGSID>
        public const string leaderboard_highscores = "CgkIifHX39oVEAIQAQ"; // <GPGSID>
        public const string achievement_skill_level_asian_kid = "CgkIifHX39oVEAIQBw"; // <GPGSID>

}

